import { useEffect } from 'react';

export default function Terms() {
  useEffect(() => {
    document.title = "Terms of Service | Stratbyte";
  }, []);

  return (
    <div className="pt-32 pb-40 min-h-screen bg-zinc-50 text-zinc-900 selection:bg-zinc-200">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        
        <div className="mb-12">
          <h1 className="text-4xl font-medium tracking-tight mb-4 text-zinc-900">Terms of Service</h1>
          <p className="text-zinc-500 text-sm font-medium">Effective Date: June 2024</p>
        </div>

        <div className="space-y-8 text-zinc-700 leading-relaxed text-sm">
          <section className="bg-white p-8 rounded-2xl border border-zinc-200 shadow-sm">
            <h2 className="text-xl font-medium tracking-tight mb-4 text-zinc-900">1. Agreement to Terms</h2>
            <p>
              By accessing stratbyte.cloud or soliciting web development, IT consulting, or hosting services from StratByte Solutions ("The Company", "We", "Us"), you agree to be bound by these corporate terms of service. If you do not agree with any of these terms, you are prohibited from utilizing our digital platforms or SLA configurations.
            </p>
          </section>

          <section className="bg-white p-8 rounded-2xl border border-zinc-200 shadow-sm">
            <h2 className="text-xl font-medium tracking-tight mb-4 text-zinc-900">2. Service Scope</h2>
            <p className="mb-4">
              StratByte Solutions provides elite digital engineering services encompassing:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-zinc-600">
              <li>Custom web interface and database architectures.</li>
              <li>Procurement of enterprise-grade hardware components.</li>
              <li>Provision of high-availability cloud hosting resources.</li>
            </ul>
          </section>

          <section className="bg-white p-8 rounded-2xl border border-zinc-200 shadow-sm">
            <h2 className="text-xl font-medium tracking-tight mb-4 text-zinc-900">3. Intellectual Property</h2>
            <p>
              All core blueprint architectures, source code frameworks, custom imagery, and visual interfaces generated by StratByte prior to project finalization remain the intellectual property of the Company. Upon full receipt of agreed payment, specific usage rights and code ownership algorithms are transferred to the client as outlined in the individualized SLA.
            </p>
          </section>

          <section className="bg-white p-8 rounded-2xl border border-zinc-200 shadow-sm">
            <h2 className="text-xl font-medium tracking-tight mb-4 text-zinc-900">4. Payment & SLA Operations</h2>
            <p>
              All service deployments and server allocations require upfront payment thresholds as defined in the quotation brief. Failure to maintain subscription channels for managed hosting may result in automated instance suspension after a 14-day grace period.
            </p>
          </section>

          <section className="bg-white p-8 rounded-2xl border border-zinc-200 shadow-sm">
            <h2 className="text-xl font-medium tracking-tight mb-4 text-zinc-900">5. Limitation of Liability</h2>
            <p>
              Under no circumstance shall StratByte Solutions be liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to utilize our generated code, hosting servers, or procured hardware. Our liability strictly defaults to the total value of the specific service invoice in question.
            </p>
          </section>

          <section className="bg-white p-8 rounded-2xl border border-zinc-200 shadow-sm">
            <h2 className="text-xl font-medium tracking-tight mb-4 text-zinc-900">6. Modifications</h2>
            <p>
              We reserve the right to modify or adjust these corporate terms at our sole discretion. Continuous utilization of our services constitutes algorithmic acceptance of the revised conditions.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
